Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

## 01 VM ##
config.vm.define "centos01" do |centos01|
    centos01.vm.box = "centos/stream9"
    centos01.vm.hostname = "centos01"
    centos01.vm.network "private_network", ip: "192.168.56.20"
    centos01.vm.provider "virtualbox" do |vb|
     vb.memory = "2548"
   end

  end
end
  



