Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  
  ## 01 VM ##
  config.vm.define "ubuntu01" do |ubuntu01|
    ubuntu01.vm.box = "bento/ubuntu-24.04"
    ubuntu01.vm.hostname = "ubuntu01"
    ubuntu01.vm.network "private_network", ip: "192.168.56.25"
    ubuntu01.vm.provider "virtualbox" do |vb|
       vb.memory = "3548"
     end
  
    end
  end
    
  
  
  
  
